-- ============================================================================
-- YYME MARKETPLACE: 3-TIER CATEGORY TAXONOMY SEED SCRIPT
-- L1 Categories: 9
-- L2 Categories: 23
-- L3 Categories: 93
-- ============================================================================

-- 1. LEVEL 1 (PRIMARY CATEGORIES)
INSERT INTO public.categories (category_id, parent_category_id, level, name, display_order)
VALUES
  ('l1-handicrafts-and-artisanal', NULL, 1, 'Handicrafts & Artisanal', 1),
  ('l1-diy-and-home-crafted-supplies', NULL, 1, 'DIY & Home-Crafted Supplies', 2),
  ('l1-fashion', NULL, 1, 'Fashion', 3),
  ('l1-electronics', NULL, 1, 'Electronics', 4),
  ('l1-home-and-living', NULL, 1, 'Home & Living', 5),
  ('l1-beauty-and-personal-care', NULL, 1, 'Beauty & Personal Care', 6),
  ('l1-sports-and-fitness', NULL, 1, 'Sports & Fitness', 7),
  ('l1-toys-and-baby-care', NULL, 1, 'Toys & Baby Care', 8),
  ('l1-books-and-stationery', NULL, 1, 'Books & Stationery', 9)
ON CONFLICT (category_id) DO UPDATE 
SET name = EXCLUDED.name, 
    level = EXCLUDED.level, 
    parent_category_id = EXCLUDED.parent_category_id, 
    display_order = EXCLUDED.display_order;

-- 2. LEVEL 2 (SUB-CATEGORIES)
INSERT INTO public.categories (category_id, parent_category_id, level, name, display_order)
VALUES
  ('l2-home-decor-and-accents', 'l1-handicrafts-and-artisanal', 2, 'Home Decor & Accents', 1),
  ('l2-handloom-and-textiles', 'l1-handicrafts-and-artisanal', 2, 'Handloom & Textiles', 2),
  ('l2-handmade-jewelry', 'l1-handicrafts-and-artisanal', 2, 'Handmade Jewelry', 3),
  ('l2-pottery-and-ceramics', 'l1-handicrafts-and-artisanal', 2, 'Pottery & Ceramics', 4),
  ('l2-wooden-and-bamboo-crafts', 'l1-handicrafts-and-artisanal', 2, 'Wooden & Bamboo Crafts', 5),
  ('l2-yarn-and-sewing', 'l1-diy-and-home-crafted-supplies', 2, 'Yarn & Sewing', 1),
  ('l2-resin-and-casting', 'l1-diy-and-home-crafted-supplies', 2, 'Resin & Casting', 2),
  ('l2-candle-and-soap-making', 'l1-diy-and-home-crafted-supplies', 2, 'Candle & Soap Making', 3),
  ('l2-men-s-fashion', 'l1-fashion', 2, 'Men''s Fashion', 1),
  ('l2-women-s-fashion', 'l1-fashion', 2, 'Women''s Fashion', 2),
  ('l2-kids-fashion', 'l1-fashion', 2, 'Kids'' Fashion', 3),
  ('l2-mobile-and-tablets', 'l1-electronics', 2, 'Mobile & Tablets', 1),
  ('l2-computers-and-laptops', 'l1-electronics', 2, 'Computers & Laptops', 2),
  ('l2-home-appliances', 'l1-electronics', 2, 'Home Appliances', 3),
  ('l2-living-room-furniture', 'l1-home-and-living', 2, 'Living Room Furniture', 1),
  ('l2-bedding-and-linens', 'l1-home-and-living', 2, 'Bedding & Linens', 2),
  ('l2-kitchen-and-dining', 'l1-home-and-living', 2, 'Kitchen & Dining', 3),
  ('l2-organic-skincare', 'l1-beauty-and-personal-care', 2, 'Organic Skincare', 1),
  ('l2-haircare', 'l1-beauty-and-personal-care', 2, 'Haircare', 2),
  ('l2-exercise-equipment', 'l1-sports-and-fitness', 2, 'Exercise Equipment', 1),
  ('l2-outdoor-recreation', 'l1-sports-and-fitness', 2, 'Outdoor Recreation', 2),
  ('l2-educational-toys', 'l1-toys-and-baby-care', 2, 'Educational Toys', 1),
  ('l2-handmade-paper-and-journals', 'l1-books-and-stationery', 2, 'Handmade Paper & Journals', 1)
ON CONFLICT (category_id) DO UPDATE 
SET name = EXCLUDED.name, 
    level = EXCLUDED.level, 
    parent_category_id = EXCLUDED.parent_category_id, 
    display_order = EXCLUDED.display_order;

-- 3. LEVEL 3 (LEAF CATEGORIES)
INSERT INTO public.categories (category_id, parent_category_id, level, name, display_order)
VALUES
  ('l3-home-decor-and-accents-wall-hangings', 'l2-home-decor-and-accents', 3, 'Wall Hangings', 1),
  ('l3-home-decor-and-accents-dreamcatchers', 'l2-home-decor-and-accents', 3, 'Dreamcatchers', 2),
  ('l3-home-decor-and-accents-macrame', 'l2-home-decor-and-accents', 3, 'Macrame', 3),
  ('l3-home-decor-and-accents-ceramic-vases', 'l2-home-decor-and-accents', 3, 'Ceramic Vases', 4),
  ('l3-handloom-and-textiles-kantha-quilts', 'l2-handloom-and-textiles', 3, 'Kantha Quilts', 1),
  ('l3-handloom-and-textiles-block-print-bedspreads', 'l2-handloom-and-textiles', 3, 'Block-Print Bedspreads', 2),
  ('l3-handloom-and-textiles-hand-woven-rugs', 'l2-handloom-and-textiles', 3, 'Hand-Woven Rugs', 3),
  ('l3-handloom-and-textiles-pashmina-shawls', 'l2-handloom-and-textiles', 3, 'Pashmina Shawls', 4),
  ('l3-handmade-jewelry-terracotta-earrings', 'l2-handmade-jewelry', 3, 'Terracotta Earrings', 1),
  ('l3-handmade-jewelry-beaded-necklaces', 'l2-handmade-jewelry', 3, 'Beaded Necklaces', 2),
  ('l3-handmade-jewelry-resin-pendants', 'l2-handmade-jewelry', 3, 'Resin Pendants', 3),
  ('l3-handmade-jewelry-silver-filigree', 'l2-handmade-jewelry', 3, 'Silver Filigree', 4),
  ('l3-pottery-and-ceramics-clay-dinnerware', 'l2-pottery-and-ceramics', 3, 'Clay Dinnerware', 1),
  ('l3-pottery-and-ceramics-hand-painted-mugs', 'l2-pottery-and-ceramics', 3, 'Hand-painted Mugs', 2),
  ('l3-pottery-and-ceramics-planters', 'l2-pottery-and-ceramics', 3, 'Planters', 3),
  ('l3-pottery-and-ceramics-terracotta-statues', 'l2-pottery-and-ceramics', 3, 'Terracotta Statues', 4),
  ('l3-wooden-and-bamboo-crafts-hand-carved-boxes', 'l2-wooden-and-bamboo-crafts', 3, 'Hand-carved Boxes', 1),
  ('l3-wooden-and-bamboo-crafts-bamboo-baskets', 'l2-wooden-and-bamboo-crafts', 3, 'Bamboo Baskets', 2),
  ('l3-wooden-and-bamboo-crafts-wooden-toys', 'l2-wooden-and-bamboo-crafts', 3, 'Wooden Toys', 3),
  ('l3-wooden-and-bamboo-crafts-serving-trays', 'l2-wooden-and-bamboo-crafts', 3, 'Serving Trays', 4),
  ('l3-yarn-and-sewing-crochet-yarn', 'l2-yarn-and-sewing', 3, 'Crochet Yarn', 1),
  ('l3-yarn-and-sewing-knitting-needles', 'l2-yarn-and-sewing', 3, 'Knitting Needles', 2),
  ('l3-yarn-and-sewing-embroidery-hoops', 'l2-yarn-and-sewing', 3, 'Embroidery Hoops', 3),
  ('l3-yarn-and-sewing-fabric-paints', 'l2-yarn-and-sewing', 3, 'Fabric Paints', 4),
  ('l3-resin-and-casting-epoxy-resin', 'l2-resin-and-casting', 3, 'Epoxy Resin', 1),
  ('l3-resin-and-casting-silicone-molds', 'l2-resin-and-casting', 3, 'Silicone Molds', 2),
  ('l3-resin-and-casting-mica-powders', 'l2-resin-and-casting', 3, 'Mica Powders', 3),
  ('l3-resin-and-casting-glitter-flakes', 'l2-resin-and-casting', 3, 'Glitter Flakes', 4),
  ('l3-candle-and-soap-making-soy-wax', 'l2-candle-and-soap-making', 3, 'Soy Wax', 1),
  ('l3-candle-and-soap-making-essential-oils', 'l2-candle-and-soap-making', 3, 'Essential Oils', 2),
  ('l3-candle-and-soap-making-silicone-candle-molds', 'l2-candle-and-soap-making', 3, 'Silicone Candle Molds', 3),
  ('l3-candle-and-soap-making-soap-bases', 'l2-candle-and-soap-making', 3, 'Soap Bases', 4),
  ('l3-men-s-fashion-shirts', 'l2-men-s-fashion', 3, 'Shirts', 1),
  ('l3-men-s-fashion-t-shirts', 'l2-men-s-fashion', 3, 'T-Shirts', 2),
  ('l3-men-s-fashion-jeans', 'l2-men-s-fashion', 3, 'Jeans', 3),
  ('l3-men-s-fashion-trousers', 'l2-men-s-fashion', 3, 'Trousers', 4),
  ('l3-men-s-fashion-jackets', 'l2-men-s-fashion', 3, 'Jackets', 5),
  ('l3-women-s-fashion-dresses', 'l2-women-s-fashion', 3, 'Dresses', 1),
  ('l3-women-s-fashion-sarees', 'l2-women-s-fashion', 3, 'Sarees', 2),
  ('l3-women-s-fashion-kurtis', 'l2-women-s-fashion', 3, 'Kurtis', 3),
  ('l3-women-s-fashion-tops', 'l2-women-s-fashion', 3, 'Tops', 4),
  ('l3-women-s-fashion-skirts', 'l2-women-s-fashion', 3, 'Skirts', 5),
  ('l3-kids-fashion-rompers', 'l2-kids-fashion', 3, 'Rompers', 1),
  ('l3-kids-fashion-frocks', 'l2-kids-fashion', 3, 'Frocks', 2),
  ('l3-kids-fashion-shorts', 'l2-kids-fashion', 3, 'Shorts', 3),
  ('l3-kids-fashion-school-uniforms', 'l2-kids-fashion', 3, 'School Uniforms', 4),
  ('l3-mobile-and-tablets-smartphones', 'l2-mobile-and-tablets', 3, 'Smartphones', 1),
  ('l3-mobile-and-tablets-feature-phones', 'l2-mobile-and-tablets', 3, 'Feature Phones', 2),
  ('l3-mobile-and-tablets-tablets', 'l2-mobile-and-tablets', 3, 'Tablets', 3),
  ('l3-mobile-and-tablets-power-banks', 'l2-mobile-and-tablets', 3, 'Power Banks', 4),
  ('l3-computers-and-laptops-gaming-laptops', 'l2-computers-and-laptops', 3, 'Gaming Laptops', 1),
  ('l3-computers-and-laptops-ultrabooks', 'l2-computers-and-laptops', 3, 'Ultrabooks', 2),
  ('l3-computers-and-laptops-monitors', 'l2-computers-and-laptops', 3, 'Monitors', 3),
  ('l3-computers-and-laptops-keyboards', 'l2-computers-and-laptops', 3, 'Keyboards', 4),
  ('l3-home-appliances-refrigerators', 'l2-home-appliances', 3, 'Refrigerators', 1),
  ('l3-home-appliances-washing-machines', 'l2-home-appliances', 3, 'Washing Machines', 2),
  ('l3-home-appliances-microwaves', 'l2-home-appliances', 3, 'Microwaves', 3),
  ('l3-home-appliances-acs', 'l2-home-appliances', 3, 'ACs', 4),
  ('l3-living-room-furniture-sofas', 'l2-living-room-furniture', 3, 'Sofas', 1),
  ('l3-living-room-furniture-coffee-tables', 'l2-living-room-furniture', 3, 'Coffee Tables', 2),
  ('l3-living-room-furniture-tv-units', 'l2-living-room-furniture', 3, 'TV Units', 3),
  ('l3-living-room-furniture-bookshelves', 'l2-living-room-furniture', 3, 'Bookshelves', 4),
  ('l3-bedding-and-linens-bedsheets', 'l2-bedding-and-linens', 3, 'Bedsheets', 1),
  ('l3-bedding-and-linens-duvet-covers', 'l2-bedding-and-linens', 3, 'Duvet Covers', 2),
  ('l3-bedding-and-linens-blankets', 'l2-bedding-and-linens', 3, 'Blankets', 3),
  ('l3-bedding-and-linens-curtains', 'l2-bedding-and-linens', 3, 'Curtains', 4),
  ('l3-kitchen-and-dining-cookware', 'l2-kitchen-and-dining', 3, 'Cookware', 1),
  ('l3-kitchen-and-dining-dinner-sets', 'l2-kitchen-and-dining', 3, 'Dinner Sets', 2),
  ('l3-kitchen-and-dining-blenders', 'l2-kitchen-and-dining', 3, 'Blenders', 3),
  ('l3-kitchen-and-dining-cutlery', 'l2-kitchen-and-dining', 3, 'Cutlery', 4),
  ('l3-organic-skincare-handmade-soaps', 'l2-organic-skincare', 3, 'Handmade Soaps', 1),
  ('l3-organic-skincare-herbal-face-packs', 'l2-organic-skincare', 3, 'Herbal Face Packs', 2),
  ('l3-organic-skincare-lip-balms', 'l2-organic-skincare', 3, 'Lip Balms', 3),
  ('l3-organic-skincare-body-butters', 'l2-organic-skincare', 3, 'Body Butters', 4),
  ('l3-haircare-shampoos', 'l2-haircare', 3, 'Shampoos', 1),
  ('l3-haircare-conditioners', 'l2-haircare', 3, 'Conditioners', 2),
  ('l3-haircare-hair-oils', 'l2-haircare', 3, 'Hair Oils', 3),
  ('l3-haircare-hair-dryers', 'l2-haircare', 3, 'Hair Dryers', 4),
  ('l3-exercise-equipment-treadmills', 'l2-exercise-equipment', 3, 'Treadmills', 1),
  ('l3-exercise-equipment-dumbbells', 'l2-exercise-equipment', 3, 'Dumbbells', 2),
  ('l3-exercise-equipment-yoga-mats', 'l2-exercise-equipment', 3, 'Yoga Mats', 3),
  ('l3-exercise-equipment-resistance-bands', 'l2-exercise-equipment', 3, 'Resistance Bands', 4),
  ('l3-outdoor-recreation-tents', 'l2-outdoor-recreation', 3, 'Tents', 1),
  ('l3-outdoor-recreation-sleeping-bags', 'l2-outdoor-recreation', 3, 'Sleeping Bags', 2),
  ('l3-outdoor-recreation-camping-stoves', 'l2-outdoor-recreation', 3, 'Camping Stoves', 3),
  ('l3-outdoor-recreation-backpacks', 'l2-outdoor-recreation', 3, 'Backpacks', 4),
  ('l3-educational-toys-wooden-puzzles', 'l2-educational-toys', 3, 'Wooden Puzzles', 1),
  ('l3-educational-toys-building-blocks', 'l2-educational-toys', 3, 'Building Blocks', 2),
  ('l3-educational-toys-stem-kits', 'l2-educational-toys', 3, 'STEM Kits', 3),
  ('l3-educational-toys-board-games', 'l2-educational-toys', 3, 'Board Games', 4),
  ('l3-handmade-paper-and-journals-leather-bound-journals', 'l2-handmade-paper-and-journals', 3, 'Leather-bound Journals', 1),
  ('l3-handmade-paper-and-journals-pressed-flower-notebooks', 'l2-handmade-paper-and-journals', 3, 'Pressed Flower Notebooks', 2),
  ('l3-handmade-paper-and-journals-calligraphy-pens', 'l2-handmade-paper-and-journals', 3, 'Calligraphy Pens', 3)
ON CONFLICT (category_id) DO UPDATE 
SET name = EXCLUDED.name, 
    level = EXCLUDED.level, 
    parent_category_id = EXCLUDED.parent_category_id, 
    display_order = EXCLUDED.display_order;
